version: '3.8'

services:
  mariadb-4-5:
    image: docker.io/bitnami/mariadb:11.4
    container_name: moodle-4-5-mariadb
    env_file:
      - .envs/.mariadb-4-5/mariadb.env
    volumes:
      - mariadb_4_5_data:/bitnami/mariadb
    ports:
      - "3308:3306"  # Different port to avoid conflict
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - moodle-4-5-network

  moodle-4-5:
    image: docker.io/bitnami/moodle:4  # Latest Moodle 4.x version
    container_name: moodle-4-5
    env_file:
      - .envs/.moodle-4-5/moodle.env
    ports:
      - "8082:8080"   # Different port to avoid conflict
      - "8445:8443"   # Different HTTPS port
    volumes:
      - moodle_4_5_data:/bitnami/moodle
      - moodledata_4_5_data:/bitnami/moodledata
    depends_on:
      mariadb-4-5:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login/index.php"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    networks:
      - moodle-4-5-network

  # Optional Redis for session handling
  redis-4-5:
    image: docker.io/bitnami/redis:7.2
    container_name: moodle-4-5-redis
    env_file:
      - .envs/.redis-4-5/redis.env
    volumes:
      - redis_4_5_data:/bitnami/redis/data
    ports:
      - "6381:6379"  # Different port to avoid conflict
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - moodle-4-5-network

networks:
  moodle-4-5-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/24  # Different subnet from other networks

volumes:
  mariadb_4_5_data:
    driver: local
  moodle_4_5_data:
    driver: local
  moodledata_4_5_data:
    driver: local
  redis_4_5_data:
    driver: local