version: '3.8'

# Test environment for Moodle - used for testing updates, plugins, and configurations
# Isolated from production with separate database and volumes

services:
  mariadb-test:
    image: mariadb:11.4
    container_name: moodle-mariadb-test
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: test_root_pass
      MARIADB_DATABASE: moodle_test
      MARIADB_USER: moodle_test
      MARIADB_PASSWORD: test_pass_2024
      MARIADB_CHARACTER_SET: utf8mb4
      MARIADB_COLLATE: utf8mb4_unicode_ci
    volumes:
      - mariadb_test_data:/var/lib/mysql
    networks:
      - moodle-test-network
    ports:
      - "3308:3306"
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      interval: 15s
      timeout: 5s
      retries: 6

  redis-test:
    image: redis:7.2-alpine
    container_name: moodle-redis-test
    restart: unless-stopped
    command: redis-server --requirepass test_redis_pass --maxclients 500
    volumes:
      - redis_test_data:/data
    networks:
      - moodle-test-network
    ports:
      - "6380:6379"

  moodle-test:
    image: bitnami/moodle:5.0.2
    container_name: moodle-app-test
    restart: unless-stopped
    environment:
      # Database configuration
      MOODLE_DATABASE_HOST: mariadb-test
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_NAME: moodle_test
      MOODLE_DATABASE_USER: moodle_test
      MOODLE_DATABASE_PASSWORD: test_pass_2024

      # Admin configuration
      MOODLE_USERNAME: testadmin
      MOODLE_PASSWORD: Test@2024!
      MOODLE_EMAIL: test@pucsr.edu.kh
      MOODLE_SITE_NAME: "PUCSR Test Moodle"

      # Testing-specific settings
      MOODLE_SKIP_BOOTSTRAP: no
      MOODLE_DEBUG: true
      MOODLE_DEBUG_DISPLAY: true

      # Redis configuration for testing
      MOODLE_REDIS_HOST: redis-test
      MOODLE_REDIS_PORT: 6379
      MOODLE_REDIS_PASSWORD: test_redis_pass

      # PHP configuration for testing
      PHP_ENABLE_OPCACHE: no  # Disable for testing
      PHP_MEMORY_LIMIT: 512M
      PHP_MAX_EXECUTION_TIME: 600  # Longer for testing
      PHP_ERROR_REPORTING: E_ALL  # Full error reporting
      PHP_DISPLAY_ERRORS: On

      # Enable all debugging
      MOODLE_DEVELOPER_MODE: true
      MOODLE_DEBUG_LEVEL: DEVELOPER
    volumes:
      - moodle_test_data:/bitnami/moodle
      - moodledata_test_data:/bitnami/moodledata
      # Mount for testing custom code
      - ./test-plugins:/bitnami/moodle/mod/custom:ro
    ports:
      - "8082:8080"
      - "8445:8443"
    depends_on:
      mariadb-test:
        condition: service_healthy
      redis-test:
        condition: service_started
    networks:
      - moodle-test-network
    labels:
      - "environment=test"
      - "purpose=testing"

  # PHPUnit test runner for automated testing
  moodle-phpunit:
    image: bitnami/moodle:5.0.2
    container_name: moodle-phpunit
    restart: "no"
    environment:
      MOODLE_DATABASE_HOST: mariadb-test
      MOODLE_DATABASE_NAME: moodle_phpunit
      MOODLE_DATABASE_USER: moodle_test
      MOODLE_DATABASE_PASSWORD: test_pass_2024
    volumes:
      - moodle_test_data:/bitnami/moodle:ro
      - ./test-results:/test-results
    networks:
      - moodle-test-network
    command: |
      bash -c "
        cd /bitnami/moodle &&
        php admin/tool/phpunit/cli/init.php &&
        vendor/bin/phpunit --testdox > /test-results/phpunit-results.txt
      "
    profiles:
      - testing

  # Behat test runner for acceptance testing
  moodle-behat:
    image: bitnami/moodle:5.0.2
    container_name: moodle-behat
    restart: "no"
    environment:
      MOODLE_DATABASE_HOST: mariadb-test
      MOODLE_DATABASE_NAME: moodle_behat
      MOODLE_DATABASE_USER: moodle_test
      MOODLE_DATABASE_PASSWORD: test_pass_2024
      BEHAT_WWWROOT: http://moodle-test:8080
      BEHAT_DATAROOT: /bitnami/moodledata_behat
    volumes:
      - moodle_test_data:/bitnami/moodle:ro
      - moodledata_behat:/bitnami/moodledata_behat
      - ./test-results:/test-results
    networks:
      - moodle-test-network
    command: |
      bash -c "
        cd /bitnami/moodle &&
        php admin/tool/behat/cli/init.php &&
        vendor/bin/behat --format=pretty --out=/test-results/behat-results.txt
      "
    profiles:
      - testing

volumes:
  mariadb_test_data:
    driver: local
  moodle_test_data:
    driver: local
  moodledata_test_data:
    driver: local
  redis_test_data:
    driver: local
  moodledata_behat:
    driver: local

networks:
  moodle-test-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/24