version: '3.8'

# Production deployment using GitHub Container Registry (ghcr.io)
# This replaces Bitnami images with our custom hardened images

services:
  # Traefik Reverse Proxy
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=it@pucsr.edu.kh"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/letsencrypt:/letsencrypt
    networks:
      - moodle-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  # MariaDB Database (using official MariaDB with custom config)
  mariadb:
    image: mariadb:11.4
    container_name: moodle-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-changeme}
      MARIADB_DATABASE: moodle
      MARIADB_USER: moodle
      MARIADB_PASSWORD: ${DB_PASSWORD:-changeme}
      MARIADB_CHARACTER_SET: utf8mb4
      MARIADB_COLLATE: utf8mb4_unicode_ci
      MARIADB_EXTRA_FLAGS: "--max_connections=500 --innodb_buffer_pool_size=2G"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./configs/mariadb:/etc/mysql/conf.d:ro
      - ./backup-system/temp:/backup
    networks:
      - moodle-network
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      interval: 15s
      timeout: 5s
      retries: 6
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: '1.5'
        reservations:
          memory: 2G

  # Redis Cache (using official Redis Alpine)
  redis:
    image: redis:7.2-alpine
    container_name: moodle-redis
    restart: unless-stopped
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD:-changeme}
      --maxclients 10000
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --appendonly yes
      --appendfilename "redis.aof"
    volumes:
      - redis_data:/data
    networks:
      - moodle-network
    deploy:
      resources:
        limits:
          memory: 768M
          cpus: '0.5'
        reservations:
          memory: 512M

  # Moodle Application (from GHCR.io)
  moodle:
    # Use our custom image from GitHub Container Registry
    image: ghcr.io/pucsr/moodle-hardened:5.0.2
    container_name: moodle-app
    restart: unless-stopped
    environment:
      # Site configuration
      MOODLE_HOST: moodle.pucsr.edu.kh
      MOODLE_SITE_NAME: "PUCSR Moodle"
      MOODLE_REVERSEPROXY: "true"
      MOODLE_SSLPROXY: "true"

      # Database configuration
      MOODLE_DATABASE_TYPE: mariadb
      MOODLE_DATABASE_HOST: mariadb
      MOODLE_DATABASE_NAME: moodle
      MOODLE_DATABASE_USER: moodle
      MOODLE_DATABASE_PASSWORD: ${DB_PASSWORD:-changeme}

      # Admin configuration
      MOODLE_USERNAME: admin
      MOODLE_PASSWORD: ${ADMIN_PASSWORD:-changeme}
      MOODLE_EMAIL: it@pucsr.edu.kh

      # Redis configuration
      MOODLE_REDIS_HOST: redis
      MOODLE_REDIS_PORT: 6379
      MOODLE_REDIS_PASSWORD: ${REDIS_PASSWORD:-changeme}

      # PHP configuration
      PHP_MEMORY_LIMIT: 512M
      PHP_MAX_EXECUTION_TIME: 300
      PHP_POST_MAX_SIZE: 512M
      PHP_UPLOAD_MAX_FILESIZE: 512M

      # Timezone
      TZ: Asia/Phnom_Penh
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
      - ./moodle-git:/opt/moodle:ro  # Mount Git-based Moodle code
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - moodle-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.moodle.rule=Host(`moodle.pucsr.edu.kh`)"
      - "traefik.http.routers.moodle.entrypoints=websecure"
      - "traefik.http.routers.moodle.tls.certresolver=letsencrypt"
      - "traefik.http.services.moodle.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.moodle-headers.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.moodle-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.moodle-headers.headers.stsPreload=true"
      - "traefik.http.routers.moodle.middlewares=moodle-headers"
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
        reservations:
          memory: 2G
          cpus: '1'

  # Backup Service (from GHCR.io)
  backup:
    image: ghcr.io/pucsr/moodle-backup:latest
    container_name: moodle-backup
    restart: unless-stopped
    environment:
      BACKUP_SCHEDULE: "0 2 * * *"  # Daily at 2 AM
      S3_BUCKET: ${S3_BACKUP_BUCKET}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      GDRIVE_FOLDER: ${GDRIVE_FOLDER_ID}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backup-system:/backup-system
      - /backup:/backup
      - moodle_data:/data/moodle:ro
      - moodledata_data:/data/moodledata:ro
      - mariadb_data:/data/mariadb:ro
    networks:
      - moodle-network
    depends_on:
      - moodle
      - mariadb
      - redis

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /data/moodle/mariadb
      o: bind
  moodle_data:
    driver: local
    driver_opts:
      type: none
      device: /data/moodle/app
      o: bind
  moodledata_data:
    driver: local
    driver_opts:
      type: none
      device: /data/moodle/data
      o: bind
  redis_data:
    driver: local
    driver_opts:
      type: none
      device: /data/moodle/redis
      o: bind

networks:
  moodle-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24