version: '3.8'

services:
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: moodle
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    volumes:
      - db_data:/var/lib/mysql

  moodle:
    image: bitnami/moodle:latest
    restart: always
    ports:
      - "8888:8080"
    environment:
      - MOODLE_DATABASE_HOST=db
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=moodle
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=admin123
      - MOODLE_EMAIL=admin@example.com
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata:/bitnami/moodledata
    depends_on:
      - db

volumes:
  db_data:
  moodle_data:
  moodledata: