version: '3.8'

services:
  db:
    image: mariadb:10.11
    container_name: moodle-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodlepass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - moodle-net
    ports:
      - "3306:3306"

  moodle:
    image: bitnami/moodle:latest
    container_name: moodle
    restart: unless-stopped
    environment:
      MOODLE_DATABASE_HOST: db
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_NAME: moodle
      MOODLE_DATABASE_USER: moodleuser
      MOODLE_DATABASE_PASSWORD: moodlepass
      MOODLE_USERNAME: admin
      MOODLE_PASSWORD: Admin@123456
      MOODLE_EMAIL: admin@pucsr.edu.kh
      MOODLE_SITE_NAME: PUCSR Moodle
      MOODLE_HOST: moodle.pucsr.edu.kh
      PHP_MEMORY_LIMIT: 512M
      PHP_POST_MAX_SIZE: 200M
      PHP_UPLOAD_MAX_FILESIZE: 200M
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata:/bitnami/moodledata
    ports:
      - "80:8080"
      - "443:8443"
    depends_on:
      - db
    networks:
      - moodle-net

volumes:
  db_data:
  moodle_data:
  moodledata:

networks:
  moodle-net:
    driver: bridge