services:
  mariadb:
    image: mariadb:11.4
    container_name: moodle-mariadb
    restart: unless-stopped
    env_file:
      - .envs/.mariadb/mariadb.env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - moodle-network
    ports:
      - "3306:3306"
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      interval: 15s
      timeout: 5s
      retries: 6

  moodle:
    image: naga_moodle_php84:latest
    container_name: moodle-app
    restart: unless-stopped
    env_file:
      - .envs/.moodle/moodle.env
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
    ports:
      - "80:8080"
      - "443:8443"
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - moodle-network
    healthcheck:
      test: ['CMD-SHELL', 'php -r "exit(file_get_contents(\"http://localhost:8080/\") ? 0 : 1);"']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local

networks:
  moodle-network:
    driver: bridge